### PR TITLE
Add section 3-impact HTML and CSS code 

### LINKED ISSUE #26: section 3 our impact (branch name sec3-impact)
- [ ] write impact section HTML and CSS
- [ ] title
- [ ] light background
- [ ] background with shadows
- [ ] 3 cards
    - [ ] title
    - [ ] paragraph
    - [ ] background color
- [ ] send a PR
- [ ] comment in VSCode to close #26

### PR DESCRIPTION
**Pull request by AlinaTaoRao**
Add section 3-impact HTML and CSS code 
close #26
### General Checks

- [ ] the branch is up to date with `main`/`master`
- [ ] the code works when pulled and run locally
- [ ] All CI checks pass
- [ ] all conflicts are resolved (if any)
- [ ] PR has a descriptive title
- [ ] PR has appropriate labels and milestones for easy identification
- [ ] PR it is assigned to the owner
- [ ] reviewers are assigned
- [ ] the PR contributes only one focused change
- [ ] It is in the appropriate column in the project board (if necessary)
- [ ] has short and clear description
- [ ] is linked to an issue (if it is related)
- [ ] feedback is addressed (if any and if it is appropriate feedback.)

## Markdown

- [ ] the markdown source is formatted
- [ ] spelling and grammar is correct in all text
- [ ] The markdown looks correct when you preview the file
- [ ] all links and images work

### HTML

- [ ] the code is well-formatted
- [ ] the HTML code passes validation
- [ ] there are no inline styles (example: `style='color: red;'`)
- [ ] there are no `<style>` tags with CSS, all styles are hrefs
- [ ] there is no inline JavaScript (example: `onclick='doSomething()'`)
- [ ] there are no `<script>` tags with JS, all JS is in an separate file
- [ ] `id`s are used for JavaScript only, not for CSS
- [ ] semantic tags are used
- [ ] spelling and grammar is correct in all site content

### CSS

- [ ] the code is well-formatted
- [ ] passes all the linting checks

### CODE REVIEW

**Comment by AlinaTaoRao** [comment]
I tried to fix "lint checks" problems. When I sent the 1st PR, the details looks like this.
sec3-v1 error
I fixed some of the problems, and now the details looks like this.
sec3-v2
 How to fix these problems now? I don't understand the  clue. I need help. 😢

**Comment by AlinaTaoRao** [comment]
Problem solved. Read the clue in details and be patient. 😄

**Comment by sannesofie** [comment]
Your PR passes the lint check @AlinaTaoRao great 👍

**Comment by AlinaTaoRao** [comment]
@sannesofie 
Thanks. After I fixed problems in HTML and CSS one by one. I'm happy it finally passed. 😃

**Review by tahminarasoli — APPROVED** [review]

**Comment by tahminarasoli** [comment]
@AlinaTaoRao proud of you :smiley: :clap:

**Pull request merged**
